//first listening port on this client
#define OFXMULTITRACK_NODE_LISTEN_PORT 2500
#define OFXMULTITRACK_NODE_LOCAL_COUNT_MAX 10
#define OFXMULTITRACK_NODE_FRAME_AGE_MAX 0.5f
#define OFXMULTITRACK_SERVER_ALIGN_DEFAULT_TRANSFORM NonLinear
#define OFXMULTITRACK_SERVER_ALIGN_MAX_TIME_DIFFERENCE 10000
#define OFXMULTITRACK_SERVER_ALIGN_REFERENCE_JOINT "HAND_RIGHT"
#define OFXMULTITRACK_SERVER_RECORDING_MAX_FRAME_DURATION 100000
#define OFXMULTITRACK_SERVER_ORIGIN_REFERENCE_JOINT_UP "HEAD"
#define OFXMULTITRACK_SERVER_ORIGIN_REFERENCE_JOINT_RIGHT "HAND_RIGHT"
#define OFXMULTITRACK_SERVER_ORIGIN_REFERENCE_JOINT_FLOOR_LEFT "FOOT_LEFT"
#define OFXMULTITRACK_SERVER_ORIGIN_REFERENCE_JOINT_FLOOR_RIGHT "FOOT_RIGHT"
